### ISSUE TITLE
[Enhancement] Add support of auto show feature for Google Chrome

### ISSUE THREAD

**Issue by gonzaabel** [linuxmint/onboard#2]
Hi! I was testing the keyboard and it is good. I am searching one keyboard to touch screens or All in one PCs for use it with linux distributions without physical keyboard.
The idea is show it when the user is focused on any text input at least on Google Chrome. Else the keyboard should be hidden.
But the problem is it doesn't work with some apps / browsers (tested with Linux Mint 18.1 KDE Edition) like Google Chrome, Opera, and notepad cloned of Windows opened with Wine. It works with Mozilla Firefox.
The goal is can use this keyboard like on the mobiles / tablets. Thanks in advance. :smile:

**Comment by clefebvre** [comment]
Sorry, this is an upstream project: https://launchpad.net/onboard.

It isn't being developed here, this is just a copy on github to host Mint patches.
